apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: model-inference-service
  namespace: demo
  labels:
    networking.kserve.io/visibility: exposed
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 16Gi
          nvidia.com/gpu: '2'
        requests:
          cpu: '8'
          memory: 16Gi
          nvidia.com/gpu: '2'
      runtime: mistral-3-14b-instruct
      storageUri: 'pvc://pvc-decoder'
    nodeSelector:
      topology.kubernetes.io/zone: default-zone
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: NVIDIA-L40-PRIVATE
