apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-multimodal
  namespace: multimodal-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi

