apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-encoder
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
